#!/bin/bash
# Script de test pour vérifier l'auto-refresh

echo "🔄 AUTO-REFRESH TEST SCRIPT"
echo "================================"
echo ""
echo "Les 3 contrôleurs suivants ont été modifiés :"
echo ""
echo "1️⃣  SponsorAdminController.java"
echo "   ├─ ✅ Imports: ScheduledExecutorService, Executors, TimeUnit"
echo "   ├─ ✅ Variables: scheduler, REFRESH_INTERVAL_SECONDS = 5"
echo "   ├─ ✅ Méthode: startAutoRefresh()"
echo "   ├─ ✅ Méthode: stopAutoRefresh()"
echo "   ├─ ✅ Méthode: refreshDataFromDatabase()"
echo "   └─ ✅ Appelé dans: initialize()"
echo ""
echo "2️⃣  BudgetListController.java"
echo "   ├─ ✅ Même structure"
echo "   ├─ ✅ Rafraîchit aussi les graphiques"
echo "   └─ ✅ Met à jour KPI + charts"
echo ""
echo "3️⃣  DepenseListController.java"
echo "   ├─ ✅ Même structure"
echo "   ├─ ✅ Rafraîchit le graphique PieChart"
echo "   └─ ✅ Met à jour KPI + graphique"
echo ""
echo "================================"
echo "🚀 POUR TESTER :"
echo ""
echo "1. Compiler le projet:"
echo "   ./mvnw.cmd clean compile"
echo ""
echo "2. Lancer l'application:"
echo "   ./mvnw.cmd javafx:run"
echo ""
echo "3. Consulter les logs:"
echo "   Cherchez: ✅ Auto-refresh [Module] démarré"
echo ""
echo "4. Ajouter/modifier des données"
echo "   Les changements apparaîtront dans l'interface en <5s"
echo ""
echo "================================"
echo "✨ CHAQUE MODULE SE RAFRAÎCHIT :"
echo "   • Sponsor Admin : tous les 5s"
echo "   • Budget       : tous les 5s"
echo "   • Dépenses     : tous les 5s"
echo ""
echo "================================"

